# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    # paths:
      #- 'R/**'
      #- 'vignettes/**'
      #- 'tests/**'
      #- 'data/**'
      #- 'inst/**'
      #- 'man/**'
      #- 'DESCRIPTION'
      #- 'NAMESPACE'

  pull_request:
    branches: [main, master, renv]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release', pkg-type: 'binary', renv: ''}
          - {os: windows-latest, r: 'release', pkg-type: 'binary', renv: ''}
          - {os: windows-latest, r: '3.6', pkg-type: 'binary', renv: 'dev3'}
          - {os: ubuntu-latest,   r: 'devel', pkg-type: 'source', renv: ''}
          - {os: ubuntu-latest,   r: 'release', pkg-type: 'source', renv: ''}
          - {os: ubuntu-latest,   r: 'oldrel-1', pkg-type: 'source', renv: ''}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_PKG_TYPE: ${{ matrix.config.pkg-type }}
      RENV_PROFILE: ${{ matrix.config.renv }}
      CI: true
      _R_CHECK_FORCE_SUGGESTS_: false
      _R_CHECK_CRAN_INCOMING_REMOTE_: false
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_RD_XREFS_: true
      R_KEEP_PKG_SOURCE: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RGL_USE_NULL: 'TRUE'
      DISPLAY: ':1.1'

    steps:
      - uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v1

      - name: Install makeindex
        run: |
          tlmgr update --self
          tlmgr install makeindex

      - name: Test latex
        shell: bash
        run: |
          pdflatex --version
          makeindex

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -yq libglu1-mesa-dev freeglut3-dev mesa-common-dev libcurl4-openssl-dev libxml2-dev libharfbuzz-dev libfribidi-dev
          Xvfb :1 -screen 1 1024x768x24 -ac &

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install --cask xquartz
          sudo /usr/X11/bin/xvfb :1 -screen 1 1024x768x24 -ac &

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Check
        shell: Rscript {0}
        run: rcmdcheck::rcmdcheck(args = c("--as-cran"), error_on = "warning", check_dir = "check")

      - name: Show testthat output
        shell: bash
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
