# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    paths:
      - '**/test-coverage.yaml'
      - 'R/**'
      - 'tests/**'
      - 'DESCRIPTION'
      - 'NAMESPACE'
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NOT_CRAN: true
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install Linux dependencies
        run: sudo apt-get install -yq libglu1-mesa-dev libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - uses: r-lib/actions/setup-renv@v1
        with:
          cache-version: 2

      - name: Test coverage
        shell: Rscript {0}
        run: covr::codecov()
